# Generated by Django 3.2.9 on 2021-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_ID', models.CharField(max_length=20)),
                ('movie_Title', models.CharField(max_length=50)),
                ('movie_Year', models.CharField(max_length=20)),
            ],
        ),
    ]
