# Generated by Django 3.2.9 on 2021-12-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_ID',
        ),
    ]
